from __future__ import annotations
from abc import ABC, abstractmethod
from src.domain.entities.task_dependency import TaskDependency

class TaskDependencyRepository(ABC):
    @abstractmethod
    def find_by_task(self, task_id: int) -> list[TaskDependency]: ...
    @abstractmethod
    def find_all_successors(self, predecessor_id: int) -> list[TaskDependency]: ...
    @abstractmethod
    def save(self, dep: TaskDependency) -> TaskDependency: ...
    @abstractmethod
    def delete(self, predecessor_id: int, successor_id: int) -> None: ...
    @abstractmethod
    def get_all_dependencies(self) -> list[TaskDependency]: ...
